export const RENTAL_RESET = 'RENTAL_RESET';
export const SET_RENTAL_ACCOUNT = 'SET_RENTAL_ACCOUNT';
export const GET_AGREEMENTS = 'GET_AGREEMENTS';
export const GET_RENTABLE_DEVICES = 'GET_RENTABLE_DEVICES';
export const ACCEPT_RENTAL_AGREEMENT = 'ACCEPT_RENTAL_AGREEMENT';
export const TERMINATE_RENTAL_AGREEMENT = 'TERMINATE_RENTAL_AGREEMENT';
export const ADD_REQUEST = 'ADD_REQUEST';
export const GET_REQUESTS = 'GET_REQUESTS';
export const ADD_AGREEMENT = 'ADD_AGREEMENT';
export const RENTAL_ERROR = 'RENTAL_ERROR';
export const ADD_TEST_RENTAL_AGREEMENTS = 'ADD_TEST_RENTAL_AGREEMENTS';

export const IDENTITY_RESET = 'IDENTITY_RESET';
export const SET_OWN_IDENTITY = 'SET_OWN_IDENTITY';
export const GET_KNOWN_DEVICES = 'GET_KNOWN_DEVICES';
export const GET_KNOWN_MANUFACTURERS = 'GET_KNOWN_MANUFACTURERS';
export const GET_KNOWN_SERVICEPROVIDERS = 'GET_KNOWN_SERVICEPROVIDERS';
export const GET_KNOWN_SUPPLIERS = 'GET_KNOWN_SUPPLIERS';
export const ADD_IDENTITY = 'ADD_IDENTITY';
export const ADD_IDENTITIES = 'ADD_IDENTITIES';
export const IDENTITY_ERROR = 'IDENTITY_ERROR';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const GET_PAYMENT_HISTORY = 'GET_PAYMENT_HISTORY';
export const CHARGE = 'CHARGE';
export const GET_PAYMENT_DATA = 'GET_PAYMENT_DATA';
export const REDEEM = 'REDEEM';
export const SET_PAYMENT_ACCOUNT = 'SET_PAYMENT_ACCOUNT';
export const GET_BALANCE = 'GET_BALANCE';
